title: Ldom.net
description: "Donec ullamcorper nulla non <a href='https://apple.com'>metus auctor</a> fringilla."
url: https://ldom.net
baseurl: "/"

# markdown      : kramdown
# highlighter   : rouge
permalink: /:categories/:title/
encoding: utf-8
destination: _site
lang: 'en'             # The language setting is used in /includes/header.html for html-settings

remote_theme: Phlow/simplicity

# Frontpage-Layout-Settings
posts_with_teaser_limit: 1     # Define how many posts should be shown with headline, teaser, image, video
posts_list_limit: 15    # Define how many posts should be shown in the list beneath the post(s)
excerpt_separator: <!--more-->   # Use <!--more--> in your posts to generate an excerpt and a teaser

#   Choose one of the following color schemes. Available color schemes:
#  - simplicity
#  - gloom_contrast
#  - glowfish
#  - legacy
#  - yule
color_scheme: simplicity

#   Choose one of the following font combinations:
#
#   import is necessary to import the font from google
#   the settings for the fonts are used in /assets/css/simplicity.scss
font:
  import: 'Source+Code+Pro|Source+Sans+Pro:400,400italic,700,700italic'
#  import: 'Titillium+Web:400,400italic,700,700italic'
#  import: 'Roboto:400,400italic,700,700italic|Roboto+Mono'
#  import: 'Merriweather:400,400italic,700,700italic'
#  import: 'Arvo:400,400italic,700,700italic'
#  import: 'Gentium+Basic:400,400italic,700,700italic'
#  import: 'Fira+Sans:400,400italic,700,700italic|Fira+Mono'
  font-family-serif: 'Georgia, "Times New Roman", serif;'
  font-family-sans-serif: '"Source Sans Pro", "Neue Helvetica", Arial, serif;'
  base-font-family: '"Source Sans Pro", "Neue Helvetica", Arial, serif;'
  font-family-monospace: '"Source Code Pro", "Courier New", Monaco, monospace;'
  header-font-family: '"Source Sans Pro", "Neue Helvetica", Arial, serif;'

#   Choose a modular scale.
#   What is a modular scale?
#   Read this › http://alistapart.com/article/more-meaningful-typography
modular_scale: modular_scale_1em
# modular_scale: modular_scale_ratio_1_125

# Default Settings
defaults:
  -
    scope:
      path: ''        # an empty string here means all files in the project
      type: 'pages'
    values:
      layout: page      # Set default layout to page
      show_meta: false  # Hide metadata for all pages
      comments: false
      author: 'Moritz »mo.« Sauer'     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: page      # Set default layout to page
      show_meta: true   # Show metadata for all posts
      comments: false
      author: 'Moritz »mo.« Sauer'     # Default author for posts

# google_site_verification: 'Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ'

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'


sass:
    sass_dir: _sass
    style: :compressed


# disqus_shortname:

# google_analytics_tracking_id:

socialmedia:
    youtube: ldom17
    github: ldom
    twitter: ldom
    # tumblr: motizen
    instagram: ldom
    # rss: # Full URL needed

plugins:
    - jekyll-gist
    - jekyll-sitemap
    - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings : all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]
